name: "Compile Check"

on:
  workflow_call:
    inputs:
      reason:
        description: 'Reason for triggering compile check'
        required: false
        type: string
        default: 'Manual trigger'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running'
        required: false
        default: 'Manual trigger'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build-essential
      run: sudo apt-get update && sudo apt-get install -y build-essential && sudo apt-get install -y libreadline-dev

    - name: Compile with Make
      run: make CC="cc" CFLAGS="-Wall -Wextra -Werror -lreadline"
