name: "Norminette"

on:
  workflow_call:
    inputs:
      reason:
        description: 'Reason for triggering norminette'
        required: false
        type: string
        default: 'Manual trigger'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running'
        required: false
        default: 'Manual security scan'

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hanshazairi/42-norminette-action@v1.1.0
        with:
          exclude-dir: './.github'
